/**
 * generated by Xtext 2.32.0
 */
package fr.n7.chaiseMinute.cHAISEMINUTETEXT.tests;

import fr.n7.chaiseMinute.cHAISEMINUTETEXT.CHAISEMINUTETEXTFactory;
import fr.n7.chaiseMinute.cHAISEMINUTETEXT.ChaiseMinute;

import junit.framework.TestCase;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Chaise Minute</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class ChaiseMinuteTest extends TestCase {

	/**
	 * The fixture for this Chaise Minute test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChaiseMinute fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(ChaiseMinuteTest.class);
	}

	/**
	 * Constructs a new Chaise Minute test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ChaiseMinuteTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Chaise Minute test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(ChaiseMinute fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Chaise Minute test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChaiseMinute getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(CHAISEMINUTETEXTFactory.eINSTANCE.createChaiseMinute());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //ChaiseMinuteTest
