/**
 * generated by Xtext 2.32.0
 */
package fr.n7.chaiseMinute.cHAISEMINUTETEXT.tests;

import fr.n7.chaiseMinute.cHAISEMINUTETEXT.CHAISEMINUTETEXTFactory;
import fr.n7.chaiseMinute.cHAISEMINUTETEXT.ImportedColumn;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Imported Column</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class ImportedColumnTest extends ColumnTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(ImportedColumnTest.class);
	}

	/**
	 * Constructs a new Imported Column test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ImportedColumnTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Imported Column test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected ImportedColumn getFixture() {
		return (ImportedColumn)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(CHAISEMINUTETEXTFactory.eINSTANCE.createImportedColumn());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //ImportedColumnTest
