/*
 * generated by Xtext 2.32.0
 */
package fr.n7.chaiseMinute.parser.antlr;

import com.google.inject.Inject;
import fr.n7.chaiseMinute.parser.antlr.internal.InternalFromTextParser;
import fr.n7.chaiseMinute.services.FromTextGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class FromTextParser extends AbstractAntlrParser {

	@Inject
	private FromTextGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFromTextParser createParser(XtextTokenStream stream) {
		return new InternalFromTextParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ChaiseMinute";
	}

	public FromTextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FromTextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
