/**
 * generated by Xtext 2.32.0
 */
package fr.n7.chaiseMinute.tabouretSeconde.tabouretSeconde.impl;

import fr.n7.chaiseMinute.tabouretSeconde.tabouretSeconde.Algorithm;
import fr.n7.chaiseMinute.tabouretSeconde.tabouretSeconde.ChaiseMinute;
import fr.n7.chaiseMinute.tabouretSeconde.tabouretSeconde.Table;
import fr.n7.chaiseMinute.tabouretSeconde.tabouretSeconde.TabouretSecondePackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Chaise Minute</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.chaiseMinute.tabouretSeconde.tabouretSeconde.impl.ChaiseMinuteImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.chaiseMinute.tabouretSeconde.tabouretSeconde.impl.ChaiseMinuteImpl#getTables <em>Tables</em>}</li>
 *   <li>{@link fr.n7.chaiseMinute.tabouretSeconde.tabouretSeconde.impl.ChaiseMinuteImpl#getConstraints <em>Constraints</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ChaiseMinuteImpl extends MinimalEObjectImpl.Container implements ChaiseMinute
{
  /**
	 * The default value of the '{@link #getName() <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getName()
	 * @generated
	 * @ordered
	 */
  protected static final String NAME_EDEFAULT = null;

  /**
	 * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getName()
	 * @generated
	 * @ordered
	 */
  protected String name = NAME_EDEFAULT;

  /**
	 * The cached value of the '{@link #getTables() <em>Tables</em>}' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getTables()
	 * @generated
	 * @ordered
	 */
  protected EList<Table> tables;

  /**
	 * The cached value of the '{@link #getConstraints() <em>Constraints</em>}' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getConstraints()
	 * @generated
	 * @ordered
	 */
  protected EList<Algorithm> constraints;

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  protected ChaiseMinuteImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  protected EClass eStaticClass()
  {
		return TabouretSecondePackage.Literals.CHAISE_MINUTE;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public String getName()
  {
		return name;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void setName(String newName)
  {
		String oldName = name;
		name = newName;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, TabouretSecondePackage.CHAISE_MINUTE__NAME, oldName, name));
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public EList<Table> getTables()
  {
		if (tables == null) {
			tables = new EObjectContainmentEList<Table>(Table.class, this, TabouretSecondePackage.CHAISE_MINUTE__TABLES);
		}
		return tables;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public EList<Algorithm> getConstraints()
  {
		if (constraints == null) {
			constraints = new EObjectContainmentEList<Algorithm>(Algorithm.class, this, TabouretSecondePackage.CHAISE_MINUTE__CONSTRAINTS);
		}
		return constraints;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
		switch (featureID) {
			case TabouretSecondePackage.CHAISE_MINUTE__TABLES:
				return ((InternalEList<?>)getTables()).basicRemove(otherEnd, msgs);
			case TabouretSecondePackage.CHAISE_MINUTE__CONSTRAINTS:
				return ((InternalEList<?>)getConstraints()).basicRemove(otherEnd, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
		switch (featureID) {
			case TabouretSecondePackage.CHAISE_MINUTE__NAME:
				return getName();
			case TabouretSecondePackage.CHAISE_MINUTE__TABLES:
				return getTables();
			case TabouretSecondePackage.CHAISE_MINUTE__CONSTRAINTS:
				return getConstraints();
		}
		return super.eGet(featureID, resolve, coreType);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
		switch (featureID) {
			case TabouretSecondePackage.CHAISE_MINUTE__NAME:
				setName((String)newValue);
				return;
			case TabouretSecondePackage.CHAISE_MINUTE__TABLES:
				getTables().clear();
				getTables().addAll((Collection<? extends Table>)newValue);
				return;
			case TabouretSecondePackage.CHAISE_MINUTE__CONSTRAINTS:
				getConstraints().clear();
				getConstraints().addAll((Collection<? extends Algorithm>)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void eUnset(int featureID)
  {
		switch (featureID) {
			case TabouretSecondePackage.CHAISE_MINUTE__NAME:
				setName(NAME_EDEFAULT);
				return;
			case TabouretSecondePackage.CHAISE_MINUTE__TABLES:
				getTables().clear();
				return;
			case TabouretSecondePackage.CHAISE_MINUTE__CONSTRAINTS:
				getConstraints().clear();
				return;
		}
		super.eUnset(featureID);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public boolean eIsSet(int featureID)
  {
		switch (featureID) {
			case TabouretSecondePackage.CHAISE_MINUTE__NAME:
				return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
			case TabouretSecondePackage.CHAISE_MINUTE__TABLES:
				return tables != null && !tables.isEmpty();
			case TabouretSecondePackage.CHAISE_MINUTE__CONSTRAINTS:
				return constraints != null && !constraints.isEmpty();
		}
		return super.eIsSet(featureID);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public String toString()
  {
		if (eIsProxy()) return super.toString();

		StringBuilder result = new StringBuilder(super.toString());
		result.append(" (name: ");
		result.append(name);
		result.append(')');
		return result.toString();
	}

} //ChaiseMinuteImpl
