/*
 * generated by Xtext 2.32.0
 */
package fr.n7.chaiseMinute.ui;

import com.google.inject.Injector;
import fr.n7.chaiseMinute.fromText.ui.internal.FromTextActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FromTextExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(FromTextActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		FromTextActivator activator = FromTextActivator.getInstance();
		return activator != null ? activator.getInjector(FromTextActivator.FR_N7_CHAISEMINUTE_FROMTEXT) : null;
	}

}
