<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="algorithm" nsURI="http://algorithm" nsPrefix="algorithm">
  <eClassifiers xsi:type="ecore:EClass" name="Algorithm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//Argument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" lowerBound="1"
        eType="#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputLocation" eType="#//Argument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function">
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="#//Function"
        eOpposite="#//Function/next"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//Function"
        eOpposite="#//Function/previous"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//Argument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#//Operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Argument"/>
  <eClassifiers xsi:type="ecore:EClass" name="CellArgument" eSuperTypes="#//Argument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idColumn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnArgument" eSuperTypes="#//Argument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idColumn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockArgument" eSuperTypes="#//Argument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexLineStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexLineEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idColumnStart" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idColumnEnd" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineArgument" eSuperTypes="#//Argument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true"/>
</ecore:EPackage>
