/*
 * generated by Xtext 2.32.0
 */
package fr.n7.chaiseMinute.tabouretSeconde.ui.tests;

import com.google.inject.Injector;
import fr.n7.chaiseMinute.tabouretSeconde.ui.internal.TabouretSecondeActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TabouretSecondeUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TabouretSecondeActivator.getInstance().getInjector("fr.n7.chaiseMinute.tabouretSeconde.TabouretSeconde");
	}

}
