/*
 * generated by Xtext 2.32.0
 */
package fr.n7.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.n7.CHAISEMINUTETEXTRuntimeModule;
import fr.n7.CHAISEMINUTETEXTStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CHAISEMINUTETEXTIdeSetup extends CHAISEMINUTETEXTStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CHAISEMINUTETEXTRuntimeModule(), new CHAISEMINUTETEXTIdeModule()));
	}
	
}
