/*
 * generated by Xtext 2.32.0
 */
package fr.n7.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CHAISEMINUTETEXTUiModule extends AbstractCHAISEMINUTETEXTUiModule {

	public CHAISEMINUTETEXTUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
