/*
 * generated by Xtext 2.32.0
 */
package fr.n7.chaiseMinute;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FromTextRuntimeModule extends AbstractFromTextRuntimeModule {
}
