/*
 * generated by Xtext 2.32.0
 */
package fr.n7.chaiseMinute;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FromTextStandaloneSetup extends FromTextStandaloneSetupGenerated {

	public static void doSetup() {
		new FromTextStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
