/**
 * generated by Xtext 2.32.0
 */
package fr.n7.chaiseMinute.cHAISEMINUTETEXT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Imported Column</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.chaiseMinute.cHAISEMINUTETEXT.ImportedColumn#getPath <em>Path</em>}</li>
 * </ul>
 *
 * @see fr.n7.chaiseMinute.cHAISEMINUTETEXT.CHAISEMINUTETEXTPackage#getImportedColumn()
 * @model
 * @generated
 */
public interface ImportedColumn extends Column
{
  /**
	 * Returns the value of the '<em><b>Path</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Path</em>' attribute.
	 * @see #setPath(String)
	 * @see fr.n7.chaiseMinute.cHAISEMINUTETEXT.CHAISEMINUTETEXTPackage#getImportedColumn_Path()
	 * @model
	 * @generated
	 */
  String getPath();

  /**
	 * Sets the value of the '{@link fr.n7.chaiseMinute.cHAISEMINUTETEXT.ImportedColumn#getPath <em>Path</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Path</em>' attribute.
	 * @see #getPath()
	 * @generated
	 */
  void setPath(String value);

} // ImportedColumn
