<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="chaiseMinute" nsURI="http://chaiseMinute" nsPrefix="chaiseMinute">
  <eClassifiers xsi:type="ecore:EClass" name="ChaiseMinute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1"
        eType="#//Table" containment="true" eOpposite="#//Table/chaiseMinute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//AbstractColumn" containment="true" eOpposite="#//AbstractColumn/table"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chaiseMinute" lowerBound="1"
        eType="#//ChaiseMinute" eOpposite="#//ChaiseMinute/tables"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractColumn" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" upperBound="-1"
        eType="#//Cell" containment="true" eOpposite="#//Cell/column"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" eType="#//Table"
        eOpposite="#//Table/columns"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnData" eSuperTypes="#//AbstractColumn"/>
  <eClassifiers xsi:type="ecore:EClass" name="DerivatedColumn" eSuperTypes="#//AbstractColumn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="ecore:EClass ../fr.n7.chaiseMinute.script/algorithm.ecore#//Algorithm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" eType="ecore:EClass ../fr.n7.chaiseMinute.script/algorithm.ecore#//ColumnArgument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cell">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" lowerBound="1"
        eType="#//AbstractColumn" eOpposite="#//AbstractColumn/cells"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataType">
    <eLiterals name="String"/>
    <eLiterals name="Int" value="1"/>
  </eClassifiers>
</ecore:EPackage>
