/*
 * generated by Xtext 2.32.0
 */
package fr.n7.chaiseMinute.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FromTextUiModule extends AbstractFromTextUiModule {

	public FromTextUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
