/*
 * generated by Xtext 2.32.0
 */
package fr.n7.chaiseMinute.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFromTextScopeProvider extends DelegatingScopeProvider {
}
