/*
 * generated by Xtext 2.32.0
 */
package fr.n7.chaiseMinute.tabouretSeconde.ide;


/**
 * Use this class to register ide components.
 */
public class TabouretSecondeIdeModule extends AbstractTabouretSecondeIdeModule {
}
