/**
 * generated by Xtext 2.32.0
 */
package fr.n7.chaiseMinute.tabouretSeconde.tabouretSeconde.tests;

import fr.n7.chaiseMinute.tabouretSeconde.tabouretSeconde.ColumnArgument;
import fr.n7.chaiseMinute.tabouretSeconde.tabouretSeconde.TabouretSecondeFactory;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Column Argument</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class ColumnArgumentTest extends ArgumentTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(ColumnArgumentTest.class);
	}

	/**
	 * Constructs a new Column Argument test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ColumnArgumentTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Column Argument test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected ColumnArgument getFixture() {
		return (ColumnArgument)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(TabouretSecondeFactory.eINSTANCE.createColumnArgument());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //ColumnArgumentTest
