/*
 * generated by Xtext 2.32.0
 */
package fr.n7.chaiseMinute.tabouretSeconde;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TabouretSecondeStandaloneSetup extends TabouretSecondeStandaloneSetupGenerated {

	public static void doSetup() {
		new TabouretSecondeStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
