/*
 * generated by Xtext 2.32.0
 */
package fr.n7.ui;

import com.google.inject.Injector;
import fr.n7.chaiseMinute.text.ui.internal.TextActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CHAISEMINUTETEXTExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TextActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TextActivator activator = TextActivator.getInstance();
		return activator != null ? activator.getInjector(TextActivator.FR_N7_CHAISEMINUTETEXT) : null;
	}

}
